environment: nts
fqdn: lsst-nts-k8s.ncsa.illinois.edu
vault_path_prefix: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu

argo:
  enabled: true
alert_stream_schema_registry:
  enabled: false
cachemachine:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: true
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
semaphore:
  enabled: false
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: false
tap:
  enabled: false
tap_schema:
  enabled: false
vault_secrets_operator:
  enabled: true
