telegraf:
  config:
    agent:
      omit_hostname: true
    global_tags:
      cluster: ''
  env:
  - name: INFLUX_TOKEN
    valueFrom:
      secretKeyRef:
        key: influx-token
        name: telegraf
  podLabels:
    hub.jupyter.org/network-access-hub: 'true'
  service:
    enabled: false
  tplVersion: 2
vaultSecretsPath: ''
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
