{{- if .Values.alert_stream_broker.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: alert-stream-broker
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-stream-broker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: alert-stream-broker
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/alert-stream-broker
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    helm:
    helm:
      parameters:
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vault_path_prefix | quote }}
      valueFiles:
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
{{- end -}}
