{{- if .Values.vault_secrets_operator.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/vault-secrets-operator
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    helm:
    helm:
      parameters:
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vault_path_prefix | quote }}
      valueFiles:
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
{{- end -}}
