apiVersion: v1
kind: ConfigMap
metadata:
  name: "atlantis"
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
data:
  server-config.yaml: |
    {{- toYaml .Values.config.serverConfig | nindent 4 }}
  repo-config.yaml: |
    {{- toYaml .Values.config.repoConfig | nindent 4 }}
