apiVersion: v1
kind: ServiceAccount
metadata:
  name: "atlantis"
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "config.serviceAccountReadonly must be set to a valid Google service account" .Values.config.googleServiceAccount | quote }}
