apiVersion: v1
kind: Service
metadata:
  name: atlantis
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: "http"
  selector:
    {{- include "atlantis.selectorLabels" . | nindent 4 }}
