apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "atlantis"
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/atlantis"
  type: "Opaque"
