narrativelog:
  pull_secret: pull-secret

  site_id: base

  ingress:
    enabled: true
    annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    hosts:
      - host: base-lsp.lsst.codes
        paths:
          - /narrativelog
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

vault_path: secret/k8s_operator/base-lsp.lsst.codes/postgres

pull-secret:
  enabled: true
  path: secret/k8s_operator/base-lsp.lsst.codes/pull-secret
