apiVersion: v2
name: semaphore
version: 1.0.0
appVersion: "tickets-DM-34344"
type: application
description: Semaphore is the user notification and messaging service for the Rubin Science Platform.
sources:
  - https://github.com/lsst-sqre/semaphore
maintainers:
  - name: jonathansick
    url: https://github.com/jonathansick

dependencies:
  - name: pull-secret
    version: 0.1.2
    repository: https://lsst-sqre.github.io/charts/
