{{- if .Values.ingress.enabled -}}
{{- $path := .Values.ingress.path | default "/" -}}
{{- $isSubPath := ne $path "/" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lsst-indigo-iam.fullname" . }}
  labels: {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/configuration-snippet: |
    #  proxy_redirect ~^/(.*)$ /iam/$1;

    {{- if $isSubPath }}
    nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ $path | quote }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      secretName: tls-secret
  rules:
    - host: {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          # - path: "/webjars/(.*)"
          #   pathType: "ImplementationSpecific"
          #   backend:
          #     service:
          #       name: {{ .Values.global.iam.serviceName }}
          #       port:
          #         number: {{ .Values.container.port }}
          # - path: "/resources/(.*)"
          #   pathType: "ImplementationSpecific"
          #   backend:
          #     service:
          #       name: {{ .Values.global.iam.serviceName }}
          #       port:
          #         number: {{ .Values.container.port }}
          - path: {{ printf "%s(/|$)(.*)" $path | quote }}
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ .Values.global.iam.serviceName }}
                port:
                  number: {{ .Values.container.port }}
{{- end }}
