apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lsst-indigo-iam.fullname" . }}
  labels: {{ include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class | default "" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentvolume.size | default "5Gi" }}
