apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.iam.serviceName }}
  labels: {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  #clusterIP: None #ClusterIP
  selector:
    {{- include "lsst-indigo-iam.selectorLabels" . | nindent 6 }}
  ports:
  - port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
    name: iam-login-service-port
