apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: json-keystore-secret
  labels:
    {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  keys:
    - "keystore.jwks"
  path: "{{ .Values.global.vaultSecretsPath }}/lsst-indigo-iam"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: mariadb-secret
  labels:
    {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  keys:
    - "root-password"
    - "user-password"
    - "user"
  path: "{{ .Values.global.vaultSecretsPath }}/lsst-indigo-iam"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: mail-secret
  labels:
    {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  keys:
    - "username"
    - "password"
    - "mail"
  path: "{{ .Values.global.vaultSecretsPath }}/lsst-indigo-iam"
  type: Opaque
{{- if .Values.oidc.enabled }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: oidc-client-secret
  labels:
    {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  keys:
    - "clientId"
    - "clientSecret"
  path: "{{ .Values.global.vaultSecretsPath }}/lsst-indigo-iam"
  type: Opaque
{{- end }}
{{- if .Values.voms.enabled }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: voms-host-cert-secret
  labels: {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
spec:
  keys:
    - "voms-hostcert.pem"
    - "voms-hostkey.pem"
  path: "{{ .Values.global.vaultSecretsPath }}/lsst-indigo-iam"
  type: Opaque
{{- end }}