{{- if .Values.voms.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.voms.nginx.configMapName }}
  labels: {{- include "lsst-indigo-iam.labels" . | nindent 4 }}
data:
  voms.conf: |
    server {
        listen {{ .Values.voms.nginx.port }} ssl;
        server_name {{ .Values.voms.ingress.host }};

        ssl_certificate     /certs/hostcert.pem;
        ssl_certificate_key /certs/hostkey.pem;
        ssl_client_certificate /etc/grid-security/certificates/ca-bundle.crt;
        ssl_verify_client on;
        ssl_verify_depth 10;

        location / {
            proxy_pass http://localhost:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-SSL-Client-Serial $ssl_client_serial;
            proxy_set_header X-SSL-Client-S-Dn $ssl_client_s_dn;
            proxy_set_header X-SSL-Client-I-Dn $ssl_client_i_dn;
            proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
            proxy_set_header X-SSL-Client-V-Start  $ssl_client_v_start;
            proxy_set_header X-SSL-Client-V-End    $ssl_client_v_end;
            proxy_set_header X-SSL-Client-Cert     $ssl_client_escaped_cert;
            proxy_set_header X-ssl_client_ee_s_dn  $ssl_client_ee_s_dn;
            proxy_set_header X-ssl_client_ee_i_dn  $ssl_client_ee_i_dn;

        }
    }
{{- end }}
