ingress-nginx:
  controller:
    config:
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "4 64k"
      proxy-body-size: "100m"
      proxy-buffer-size: "64k"
      ssl-redirect: "true"
      use-forwarded-headers: "true"
    podLabels:
      gafaelfawr.lsst.io/ingress: "true"
      hub.jupyter.org/network-access-proxy-http: "true"
    metrics:
      enabled: true

vault_certificate:
  enabled: false

pull-secret:
  enabled: true
  path: ""

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
