ingress-nginx:
  controller:
    service:
      type: ClusterIP
    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/etcd
                  operator: Exists

    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate

vault_certificate:
  enabled: true
  path: secret/k8s_operator/roe/ingress-nginx

pull-secret:
  path: secret/k8s_operator/roe/pull-secret
