ingress-nginx:
  controller:
    service:
      loadBalancerIP: "139.229.160.150"
      externalTrafficPolicy: Local

pull-secret:
  enabled: true
  path: secret/k8s_operator/summit-lsp.lsst.codes/pull-secret
