ingress-nginx:
  controller:
    service:
      type: ClusterIP
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    admissionWebhooks:
      enabled: false
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate
    metrics:
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"

vault_certificate:
  path: secret/k8s_operator/minikube.lsst.codes/ingress-nginx

pull-secret:
  path: secret/k8s_operator/minikube.lsst.codes/pull-secret
