ingress:
  host: "data-dev.lsst.eu/iam"
container:
  port: 8085
iam:
  host: "data-dev.lsst.eu/iam"
  port: 8085
  security:
    forwardHeaders: "framework"
  token:
    includeScope: "true"

mail:
  host: "zrelay.in2p3.fr"
  port: "25"
  secretName: "mail-secret"

mariadb:
  persistentvolume:
    create: false
    class: "mariadb-local-storage"
    size: 5Gi
    reclaimPolicy: Retain
redis:
  persistence:
    storageClass: "redis-rsp-localstorage"
