argo-cd:
  redis:
    enabled: true
    metrics:
      enabled: true

  controller:
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
        labels: ["name", "instance"]

  repoServer:
    metrics:
      enabled: true

  notifications:
    metrics:
      enabled: true

  server:
    metrics:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      paths:
        - /argo-cd(/|$)(.*)

    extraArgs:
      - "--basehref=/argo-cd"
      - "--insecure=true"

  configs:
    secret:
      createSecret: false
      helm.repositories: |
        - url: https://lsst-sqre.github.io/charts/
          name: lsst-sqre
        - url: https://ricoberger.github.io/helm-charts/
          name: ricoberger
        - url: https://kubernetes.github.io/ingress-nginx/
          name: ingress-nginx
        - url: https://charts.helm.sh/stable
          name: stable
        - url: https://strimzi.io/charts/
          name: strimzi

vault_secret:
  enabled: true
  path: ""

pull-secret:
  enabled: true
  path: ""


# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
