argo-cd:
  controller:
    args:
      repoServerTimeoutSeconds: "180"

  server:
    ingress:
      hosts:
        - "minikube.lsst.codes"

vault_secret:
  path: secret/k8s_operator/minikube.lsst.codes/argocd

pull-secret:
  path: secret/k8s_operator/minikube.lsst.codes/pull-secret
