telegraf-ds:
  env:
    # -- Token to communicate with Influx
    - name: INFLUX_TOKEN
      valueFrom:
        secretKeyRef:
          name: telegraf
          key: influx-token
  # Ugh, you have to duplicate this with cluster set at each site.
  override_config:
    toml: |+
      [global_tags]
        cluster = ""
        daemonset = "true"
      [agent]
        interval = "10s"
        round_interval = true
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        collection_jitter = "0s"
        flush_interval = "10s"
        flush_jitter = "0s"
        precision =  ""
        debug = false
        quiet = false
        logfile = ""
        hostname = "$HOSTNAME"
        omit_hostname = false

      [[inputs.diskio]]
      [[inputs.mem]]
      [[inputs.net]]
      [[inputs.system]]
      [[inputs.cpu]]
        percpu = true
        totalcpu = true
        collect_cpu_time = false
        report_active = false
      [[inputs.disk]]
        ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
      [[inputs.kube_inventory]]
        url = "https://kubernetes.default.svc"
        bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
        resource_include = [ "pods", "persistent_volumes", "nodes" ]
        insecure_skip_verify = true
        namespace = ""
      [[outputs.influxdb_v2]]
        bucket = "monitoring"
        organization = "square"
        token = "$INFLUX_TOKEN"
        urls = [
          "https://monitoring.lsst.codes"
        ]

# -- Path to the Vault secrets (`secret/k8s_operator/<hostname>/telegraf`)
# shared with telegraf (non-DaemonSet)
# @default -- None, must be set
vaultSecretsPath: ""
