apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: telegraf
  namespace: telegraf-ds
spec:
  # Use regular telegraf path--it's the same secret
  path: {{ .Values.vaultSecretsPath }}/telegraf
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: {{ .Values.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
