nublado2:
  jupyterhub:
    ingress:
      hosts: ["tucson-teststand.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://tucson-teststand.lsst.codes/login"

    singleuser:
      extraAnnotations:
        k8s.v1.cni.cncf.io/networks: "kube-system/auxtel-dds, kube-system/comcam-dds, kube-system/misc-dds"
      initContainers:
        - name: "multus-init"
          image: "lsstit/ddsnet4u:latest"
          securityContext:
            privileged: true

  config:
    base_url: "https://tucson-teststand.lsst.codes"
    butler_secret_path: "secret/k8s_operator/tucson-teststand.lsst.codes/butler-secret"
    pull_secret_path: "secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret"
    lab_environment:
      AUTO_REPO_URLS: "https://github.com/lsst-sqre/system-test"
      AUTO_REPO_BRANCH: "prod"
      AUTO_REPO_SPECS: "https://github.com/lsst-sqre/system-test@prod"
      LSST_DDS_INTERFACE: net1
      LSST_DDS_PARTITION_PREFIX: tucson
    volumes:
      - name: home
        nfs:
          path: /jhome
          server: nfs-jhome.tu.lsst.org
      - name: project
        nfs:
          path: /project
          server: nfs-project.tu.lsst.org
      - name: scratch
        nfs:
          path: /scratch
          server: nfs-scratch.tu.lsst.org
      - name: datasets
        nfs:
          path: /lsstdata
          server: nfs-lsstdata.tu.lsst.org
    volume_mounts:
      - name: home
        mountPath: /home
      - name: datasets
        mountPath: /datasets
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

  vault_secret_path: "secret/k8s_operator/tucson-teststand.lsst.codes/nublado2"
