apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "influxdb-enterprise.fullname" . }}-meta-pdb
spec:
  minAvailable: {{ .Values.meta.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      influxdb.influxdata.com/component: meta
